### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by sharwell** [CodeContractsDotNet/CodeContracts#2]
Currently the license is specified only in headers of source files. It would be helpful to have a license file in the repository root folder so it's immediately clear to new users.

**Comment by aarondandy** [comment]
Should also consider creating a related issue with respect to contributing. Any CLA stuff to worry about? ASP.NET could be used as an example, they have a minimal source header and spell things out pretty well.

* https://github.com/aspnet/Home/blob/master/LICENSE.txt
* https://github.com/aspnet/Home/blob/master/CONTRIBUTING.md
* https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/DelegatingStream.cs#L2

**Comment by FrancescoLogozzo** [comment]
thanks. In general we are very open (and we expect!) for contributions
I will add the license file
